# Generated by Django 4.0.4 on 2022-08-03 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('father_email', models.CharField(blank=True, max_length=200, null=True)),
                ('father_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('father_work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('father_nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('is_father_alive', models.BooleanField(default=True, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_email', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('is_mother_alive', models.BooleanField(default=True, null=True)),
                ('guardain_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardain_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardain_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_email', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_profession', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_nationalId_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_national_id', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_nationality_relation', models.CharField(blank=True, max_length=200, null=True)),
                ('home_address_district', models.CharField(blank=True, max_length=200, null=True)),
                ('home_address_village', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('role_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('level', models.CharField(blank=True, choices=[('Lower', 'Lower'), ('Middle', 'Middle'), ('Higher', 'Higher')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('academic_year', models.IntegerField(null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('name', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], default='Pending', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('student_classes', models.ManyToManyField(to='administration.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('given_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=200, null=True)),
                ('is_baptised', models.BooleanField(null=True)),
                ('has_a_disability', models.BooleanField(default=False)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('hobbies_or_skills', models.TextField(blank=True, null=True)),
                ('food_dislikes', models.TextField(blank=True, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_school_class', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='students/thumnails/')),
                ('parents_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='administration.parentsdata')),
                ('student_class', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.studentclass')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('staff_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_teacher', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('given_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('national_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('religion', models.CharField(blank=True, max_length=200, null=True)),
                ('profession', models.CharField(max_length=200)),
                ('previous_work_place', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('home_address_district', models.CharField(blank=True, max_length=200, null=True)),
                ('home_address_village', models.CharField(blank=True, max_length=200, null=True)),
                ('has_a_disability', models.BooleanField(default=False)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('hobbies_or_skills', models.TextField(blank=True, null=True)),
                ('food_dislikes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='staff/thumnails/')),
                ('staff_role', models.ManyToManyField(to='administration.staffrole')),
                ('teacher_student_classes', models.ManyToManyField(to='administration.studentclass')),
                ('teacher_subjects', models.ManyToManyField(to='administration.subjectunit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
