# Generated by Django 4.0.4 on 2022-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('administration', '0002_staff_roles_student_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='staff',
            name='other_roles',
            field=models.ManyToManyField(related_name='staff_other_roles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='other_roles',
            field=models.ManyToManyField(related_name='student_other_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='roles',
            field=models.ManyToManyField(related_name='staff_roles', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roles',
            field=models.ManyToManyField(related_name='student_roles', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='StaffRole',
        ),
    ]
