# Generated by Django 4.0.4 on 2022-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_staff_staff_role_staff_other_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectunit',
            name='name_short_form',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='level',
            field=models.CharField(blank=True, choices=[('Lower', 'Lower'), ('Higher', 'Higher')], max_length=100, null=True),
        ),
    ]
