# Generated by Django 4.0.4 on 2022-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=200, null=True),
        ),
    ]
