# Generated by Django 4.0.4 on 2022-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_term_status_alter_term_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(null=True, unique=True),
        ),
    ]
