# Generated by Django 4.0.4 on 2022-08-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_term_end_date_alter_term_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='other_roles',
        ),
        migrations.RemoveField(
            model_name='student',
            name='other_roles',
        ),
    ]
