# Generated by Django 4.0.4 on 2022-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_remove_staff_other_roles_remove_student_other_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
