# Generated by Django 4.0.4 on 2022-08-03 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('COMPANY', 'COMPANY')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(help_text='Name Of the Service', max_length=60, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short Description Of the Service', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short Description Of the Product', null=True)),
                ('initail_measure', models.CharField(blank=True, max_length=200, null=True)),
                ('initail_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumnails/')),
                ('is_published', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.category')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
