# Generated by Django 4.0.4 on 2022-08-03 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('NEW_ITEM', 'NEW_ITEM'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('REPLACE_EXISTING', 'REPLACE_EXISTING'), ('EMERGENCY', 'EMERGENCY'), ('REQUEST_BY_CONSUMER', 'REQUEST_BY_CONSUMER')], max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InwardStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='item.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OutwardStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_id', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer', to='item.consumer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('NEW_ITEM', 'NEW_ITEM'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('REPLACE_EXISTING', 'REPLACE_EXISTING'), ('EMERGENCY', 'EMERGENCY'), ('REQUEST_BY_CONSUMER', 'REQUEST_BY_CONSUMER')], max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('inward_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward', to='store.inwardstock')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='item.item')),
                ('outward_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward', to='store.outwardstock')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('requisition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='store.requisition')),
            ],
        ),
        migrations.CreateModel(
            name='CustomRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_item', models.CharField(max_length=200, null=True)),
                ('measure', models.CharField(max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('custom_requisition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_requests', to='store.customrequisition')),
            ],
        ),
    ]
