# Generated by Django 4.0.4 on 2022-08-03 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('advance_target_month', models.CharField(max_length=255)),
                ('advance_target_year', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllowancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('is_contractual', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('non_contractual_target_month', models.CharField(blank=True, max_length=255, null=True)),
                ('non_contractual_target_year', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STANDARD', 'STANDARD'), ('FUNCTIONAL', 'FUNCTIONAL'), ('EXTRA', 'EXTRA'), ('DAMAGES', 'DAMAGES'), ('DEBT', 'DEBT'), ('PERSONAL', 'PERSONAL'), ('EMERGENCY', 'EMERGENCY')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FeesPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('receipt_id', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('paid_by_name', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('paid_by_phone', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.student')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('allowance_amt', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nssf_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('advance_amt', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('salary_target_month', models.CharField(max_length=255)),
                ('salary_target_year', models.CharField(max_length=255)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_payment_record', models.ManyToManyField(to='finance.feespaymentrecord')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.student')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_target_month', models.CharField(max_length=255)),
                ('salary_target_year', models.CharField(max_length=255)),
                ('salary_payment_record', models.ManyToManyField(to='finance.salarypaymentrecord')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.payment')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('nssf_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=3)),
                ('advance_payment', models.ManyToManyField(to='finance.advancepayment')),
                ('allowance_payment', models.ManyToManyField(to='finance.allowancepayment')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fees', models.ManyToManyField(to='finance.fee')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees', to='administration.student')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualClassFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fees', models.ManyToManyField(to='finance.fee')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_fees', to='administration.studentclass')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetted_expenditure', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.incometype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
    ]
