# Generated by Django 4.0.4 on 2022-08-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_staff_email_alter_staff_national_id'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_fee', to='administration.studentclass'),
        ),
    ]
