# Generated by Django 4.0.4 on 2022-08-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fee_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypaymentrecord',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.salary'),
        ),
    ]
