# Generated by Django 4.0.4 on 2022-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_salarypaymentrecord_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='nssf_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
    ]
