# Generated by Django 4.0.4 on 2022-08-07 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0009_alter_staff_email_alter_staff_national_id'),
        ('finance', '0004_alter_salary_nssf_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='advance_target_month',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='advance_target_year',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='advancepayment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='is_contractual',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='non_contractual_target_month',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='non_contractual_target_year',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='payment_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.allowancepayment'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.AddField(
            model_name='allowancepayment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_Payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.advancepayment')),
                ('allowance_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.allowancepayment')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term')),
            ],
        ),
        migrations.CreateModel(
            name='AllowancePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('acknowlegement_id', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('is_contractual', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('non_contractual_payment_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentperiod')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('acknowlegement_id', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentperiod')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='advance_payments',
            field=models.ManyToManyField(to='finance.advancepaymentrecord'),
        ),
        migrations.AddField(
            model_name='allowancepayment',
            name='allowance_payments',
            field=models.ManyToManyField(to='finance.allowancepaymentrecord'),
        ),
        migrations.AddField(
            model_name='allowancepayment',
            name='payment_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentperiod'),
        ),
    ]
