# Generated by Django 4.0.4 on 2022-08-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_advancepayment_advance_target_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='payment_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentperiod'),
        ),
    ]
