# Generated by Django 4.0.4 on 2022-08-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_advancepayment_payment_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpaymentprofile',
            name='salary_payment_record',
        ),
        migrations.RemoveField(
            model_name='staffpaymentprofile',
            name='staff',
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.salary'),
        ),
        migrations.DeleteModel(
            name='SalaryPaymentRecord',
        ),
        migrations.DeleteModel(
            name='StaffPaymentProfile',
        ),
    ]
