# Generated by Django 4.0.4 on 2022-08-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_staffpaymentprofile_salary_payment_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentperiod',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentperiod',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
