# Generated by Django 4.0.4 on 2022-08-09 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0008_alter_paymentperiod_month_alter_paymentperiod_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancepaymentrecord',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='allowancepaymentrecord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancepaymentrecord',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allowancepaymentrecord',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowance_updatedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
