# Generated by Django 4.0.4 on 2022-08-09 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0009_allowancepaymentrecord_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepaymentrecord',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='advancepaymentrecord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancepaymentrecord',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancepaymentrecord',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_updatedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
