# Generated by Django 4.0.4 on 2022-08-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_advancepaymentrecord_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepaymentrecord',
            name='payment_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='finance.paymentperiod'),
        ),
        migrations.AlterField(
            model_name='allowancepaymentrecord',
            name='non_contractual_payment_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowances', to='finance.paymentperiod'),
        ),
    ]
