# Generated by Django 4.0.4 on 2022-08-09 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0009_alter_staff_email_alter_staff_national_id'),
        ('finance', '0011_alter_advancepaymentrecord_payment_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('repayment_period', models.IntegerField(default=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAdvanceRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('receipt_id', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('is_approved', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMonthlyAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('issued_amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('repayment_period', models.IntegerField(default=1)),
                ('is_issued', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMonthlyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monthly_allowances', models.ManyToManyField(to='finance.monthlyallowance')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='advancepaymentrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='advancepaymentrecord',
            name='payment_period',
        ),
        migrations.RemoveField(
            model_name='advancepaymentrecord',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='advancepaymentrecord',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='allowance_payments',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='payment_period',
        ),
        migrations.RemoveField(
            model_name='allowancepayment',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='allowancepaymentrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='allowancepaymentrecord',
            name='non_contractual_payment_period',
        ),
        migrations.RemoveField(
            model_name='allowancepaymentrecord',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='allowancepaymentrecord',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='allowance_payment',
        ),
        migrations.RemoveField(
            model_name='staffsalary',
            name='advance_Payment',
        ),
        migrations.RemoveField(
            model_name='staffsalary',
            name='allowance_payment',
        ),
        migrations.DeleteModel(
            name='AdvancePayment',
        ),
        migrations.DeleteModel(
            name='AdvancePaymentRecord',
        ),
        migrations.DeleteModel(
            name='AllowancePayment',
        ),
        migrations.DeleteModel(
            name='AllowancePaymentRecord',
        ),
        migrations.AddField(
            model_name='monthlyadvancerepayment',
            name='monthly_advance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='finance.staffmonthlyadvance'),
        ),
        migrations.AddField(
            model_name='monthlyadvancerepayment',
            name='payback_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_requests', to='finance.paymentperiod'),
        ),
        migrations.AddField(
            model_name='monthlyadvancerepayment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.staff'),
        ),
    ]
