# Generated by Django 4.0.4 on 2022-08-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_advancerequest_monthlyadvancerepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyallowance',
            name='is_paid_monthly',
            field=models.BooleanField(default=True),
        ),
    ]
