# Generated by Django 4.0.4 on 2022-08-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_monthlyallowance_is_paid_monthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyallowance',
            name='is_paid_monthly',
        ),
    ]
