# Generated by Django 4.0.4 on 2022-08-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_monthlyallowance_is_paid_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
