# Generated by Django 4.0.4 on 2022-08-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_monthlyallowance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyallowance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
