# Generated by Django 4.0.4 on 2022-08-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_groupcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department_roles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='departments',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Departmentrole',
        ),
    ]
